### ISSUE TITLE
Troubles with installing and app

### ISSUE THREAD

**Issue by petervandepol** [INTABiotechMJ/phenobook-server#1]
Hi,

I just managed to get Phenobook running on my server. Turned out that the admin@admin.com mentioned in the manual was user@user.com. Besides that I hacked the config.php to get rid of all dev stuff. The server is running now. 

However: I can not  use it with the app: nothing is synced. How to solve this? 

Many thanks,

Peter

**Comment by juancresc** [comment]
hi!
is the URL in the app set up? what is showing in the log details?

**Comment by petervandepol** [comment]
Thank you for your reply, Juan. The URL is set up. I had some troubles there: in "settings" under the Application URL it says "ends with trailing slash". If I end with a trailing slash I get an authentication error. Without trailing slash and  "update" I get "Uploading 0 record/'s"

Phenobook runs on a shared server at a ISP, Unfortuanately I have no access to the log files.

**Comment by petervandepol** [comment]
There are some more issues I guess. When deleting the "John Doe" user I get: 

`Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'isSuperAdmin' in 'field list'' in /home/overberg/domains/pro-overberg.nl/public_html/killer/phenobook/files/php/class/Entity.php:150 Stack trace: #0 /home/overberg/domains/pro-overberg.nl/public_html/killer/phenobook/files/php/class/Entity.php(150): PDOStatement->execute(Array) #1 /home/overberg/domains/pro-overberg.nl/public_html/killer/phenobook/logic/users/delete.php(9): Entity::update(Object(User)) #2 {main} thrown in /PATH TO WWW/public_html/killer/phenobook/files/php/class/Entity.php on line 150`

The user is not deleted then. In the database the table "user" has a field isAdmin, not isSuperAdmin. Could this be the issue?

When changing a user's details I get: 

`Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'isSuperAdmin' in 'field list'' in /PATH/public_html/killer/phenobook/files/php/class/Entity.php:150 Stack trace: #0 /PATH/public_html/killer/phenobook/files/php/class/Entity.php(150): PDOStatement->execute(Array) #1 /PATH/public_html/killer/phenobook/logic/users/edit.php(34): Entity::update(Object(User)) #2 {main} thrown in /PATH/public_html/killer/phenobook/files/php/class/Entity.php on line 150`

The user is not changed then.

Seems to me that there are a few "beauty-issues" with this software. This is a pity because it is exactly what am looking for as rose breeder.....

**Comment by juancresc** [comment]
Peter so I've fixed the provided .SQL with this new field. Do you have access to the database? you can add it to the User table as _isSuperAdmin TINYINT DEFAULT 1_.

Regarding to the connection issue, you can write my privately and we can both check how to debug it (juan.crescente at gmail). Maybe I can help you setting up a small VPS which is far more convenient.

**Comment by petervandepol** [comment]
Exellent, Juan! The SQL problems are gone and I can add, edit and delete users. Thank you. Lets solve the app issue now.
